name = "canada-budokai-academy"
type = "javascript"
main = "./.wrangler/tmp/index.js"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.production]
vars = { ENVIRONMENT = "production" }


